apiVersion: v1
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <body>

    <h1>ZADANIE 2 -- sample solution</h1>
    <p>Image: spg51/zad2:1.0.10</p>

    </body>
    </html>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: zad2-cm
